version: 2.0

general:
  branches:
    only:
      - master

defaults: &defaults
  working_directory: ~/sphinx

jobs:
  "repo-check":
    docker:
      - image: testthedocs/ttd-repo
    steps:
      - checkout
      - run:
          command: |
              /usr/local/bin/check-repo.sh

  "toctree-check":
    docker:
      - image: testthedocs/ttd-toctree
    steps:
      - checkout
      - run:
          command: |
            pwd
            ls -la
            cd docs
            /usr/local/bin/testtoctree.sh

  "html":
    docker:
      #- image: testthedocs/ttd-sphinx-ci
      - image: testthedocs/ttd-sphinx
    <<: *defaults
    steps:
      - checkout
      - run:
          command: |
            # latest commit
            #LATEST_COMMIT=$(git rev-parse HEAD)

            # latest commit where someting in docs was changed
            #FOLDER_COMMIT=$(git log -1 --format=format:%H --full-diff docs)
            #if [ $FOLDER_COMMIT = $LATEST_COMMIT ]; then
            #  echo "changes, let's run the tests on docs"
              sphinx-build -c docs -b html docs docs/_build/html
            #else
            #  echo "no changes"
            #  exit 0
            #fi

      - persist_to_workspace:
          root: ~/sphinx/docs
          paths:
            - _build/html

  "deploy site":
    docker:
      - image: testthedocs/ttd-zipcurl
        #<<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/sphinx/html
      - run:
          command: |
              .circleci/deploy.sh

workflows:
  version: 2
  btd:
    jobs:
      - "repo-check"
      - "toctree-check"
      - "html":
          requires:
             - "toctree-check"
      - "deploy site":
          requires:
             - "html"
